### ISSUE TITLE
Clean up `execute()` function

### ISSUE THREAD

**Issue by aghast** [iamzumie/ghost-mansion#1]
The `execute` function currently has a return type and a special case for the `quit` command.

In `main`, move the call to `execute` to the body of the while loop. Then eliminate the return value -- make `execute` return void. Finally, create a global variable to indicate whether or not to keep playing. Something like:

    while (still_playing) {
        read_line();
        execute();
    }

With this new structure, the handling for the `quit` verb should be identical to the transitive verbs below it. You will pass in the noun, but it simply won't be used. Instead, typing `quit` will just change the `still_playing` variable to `false` and return, and the `while` loop will exit when `execute()` returns to it.

**Comment by iamzumie** [comment]
I cleaned up the execute statement.
