### ISSUE TITLE
Create enum flags for noun sources

### ISSUE THREAD

**Issue by aghast** [iamzumie/ghost-mansion#2]
Create a set of `enum` flags for searching for noun objects. This will be part of the verb structure, used by `execute` to locate verb objects.

I can think of three possible sources for a noun: a location title, the player's inventory, or the current room's inventory.

Each verb taking an object (noun) will specify where the object can come from. For example, "take" would not accept location names -- you cannot "take kitchen". You might cause it to accept items in the player's inventory, in order to provide a custom error message:  "take lamp" -> "ok" -> "take lamp" -> "you are already holding the lamp!"

Similarly, "go" would only accept location names, and not items in the room or in the player's inventory.

So each verb would have a flags `unsigned` like `{ "take", OS_ROOM_ITEMS | OS_INVENTORY, ... }`

Then write finder functions to match nouns to items:

    if (verb->flags & OS_ROOM_ITEMS) != 0
        && (item = find_item_in_room(noun)) != NULL)
    {
        verb->handler_func(noun, item, OS_ROOM_ITEMS);
    }

This can be made iterative, of course, by looping over the possible sources:

    for (os = 0; os < OS_NUM_SOURCES; ++os) {
        if (verb->flags & os_source[os] && (item = find_item(os_source[os])) != NULL) {
            verb->handler_func(noun, item, os_source[os]);
            break;
        }
    }

This would be part of your `execute()` function, making all verb handling automatic. If you have a noun, but cannot find it in one of the valid sources, then you can print the snark message you currently have at the bottom of each verb function:

    printf("I don't understand %s\n", verb->bad_object_msg);

This makes the `execute()` function slightly larger:

    static void execute(char * buffer)
    {
        char * verb = strtok(buffer, " \n");
        char * noun = strtok(NULL, " \n");

        for (VERBS * cmd = verbs; cmd < verbs + sizeof(verbs) / sizeof(VERBS); ++cmd) 
        {
            if (strcasecmp(verb, cmd->word) != 0)
                continue;

            for (os = 0; os < OS_NUM_SOURCES; ++os) 
            {
                if (cmd->flags & os_source[os] 
                    && (item = find_item(os_source[os], noun)) != NULL) 
                {
                    cmd->vb_handler(noun, item, os_source[os]);
                    return;
                }
            }

            printf("I don't understand %s\n", cmd->vb_bad_object_msg);            
        }

        puts("I don't understand what you mean, try again.\n");
    }

**Comment by iamzumie** [comment]
I've been working on trying to use pointers to structs inside structs but haven't managed to get it working. I tried it with a test project first to focus learning that but it fails.

I used a different location to test: [link](https://github.com/iamzumie/operation-wurfeld/blob/master/main.c)

**Comment by aghast** [comment]
This issue is resolved by the #4 pull request. The OSF_ flags enum is what this is about.
